#### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

### Importing the dataset

In [2]:
df  = pd.read_csv('ecommerce_dataset.csv')
df.head()

,order_id,customer_id,customer_name,email,phone_number,gender,city,product_category,product_name,price,quantity,discount,final_amount,payment_method,order_status,customer_rating,shipping_days,order_date,delivery_date,pincode
0,ORD100000,16795,Priya Sharma,priya.sharma678@gmail.com,6920626990,male,Chennai,Fashion,Coffee Maker,2930.24,2,0.46,3164.66,Credit Card,Shipped,2.0,14,2023-10-03,11-02-2022,400001.0
1,ORD100001,1860,Arjun Reddy,arjun.reddy618@gmail.com,7710434697,Female,Delhi,Groceries,Running Shoes,1829.71,7,0.26,9477.90,UPI,Shipped,NaN,17,2022-04-25,08-12-2024,0.0
2,ORD100002,39158,Sneha Khan,NaN,6647628669,male,Kolkata,NaN,Office Chair,3009.13,5,0.56,6620.09,UPI,Shipped,3.0,11,2023-12-08,22-08-2024,751001.0
3,ORD100003,45732,Priya Singh,priya.singh269@gmail.com,7562339125,F,Bangalore,Beauty,Smartphone,2066.98,8,0.50,8267.92,UPI,Delivered,NaN,-2,2022-01-29,12-11-2024,NaN
4,ORD100004,12284,Priya Mehta,priya.mehta751@gmail.com,9679292386,female,Hyderabad,Sports,Smartphone,1374.45,9,0.29,8782.74,Debit Card,Pending,5.0,17,2023-10-12,25-10-2023,400001.0

### Exploratory Data Analysis

In [3]:
# Checking the shape of data
df.shape

(230000, 20)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230000 entries, 0 to 229999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          230000 non-null  object
 1   customer_id       230000 non-null  int64
 2   customer_name     225898 non-null  object
 3   email             225899 non-null  object
 4   phone_number      230000 non-null  int64
 5   gender            230000 non-null  object
 6   city              225903 non-null  object
 7   product_category  225926 non-null  object
 8   product_name      230000 non-null  object
 9   price             225905 non-null  float64
 10  quantity          230000 non-null  int64
 11  discount          230000 non-null  float64
 12  final_amount      230000 non-null  float64
 13  payment_method    230000 non-null  object
 14  order_status      230000 non-null  object
 15  customer_rating   191447 non-null  float64
 16  shipping_days     230000 non-null  int64
 17  order_date        230000 non-null  object
 18  delivery_date     230000 non-null  object
 19  pincode           153492 non-null  float64
dtypes: float64(5), int64(4), object(11)
memory usage: 35.1+ MB

In [5]:
df.describe()

,customer_id,phone_number,price,quantity,discount,final_amount,customer_rating,shipping_days,pincode
count,230000.000000,2.300000e+05,225905.000000,230000.000000,230000.000000,230000.000000,191447.000000,230000.000000,153492.000000
mean,25452.843013,7.999984e+09,2455.449631,5.006978,0.299486,8611.940278,3.003515,6.982900,427496.965008
std,14123.289520,1.153008e+09,1285.980701,2.583636,0.173255,7252.046907,1.414222,7.211064,276280.852554
min,1000.000000,6.000002e+09,-7269.040000,1.000000,0.000000,-54270.130000,1.000000,-5.000000,0.000000
25%,13225.000000,7.003440e+09,1667.040000,3.000000,0.150000,3249.827500,2.000000,1.000000,400001.000000
50%,25396.000000,7.998670e+09,2485.760000,5.000000,0.300000,7033.430000,3.000000,7.000000,400001.000000
75%,37694.000000,8.998646e+09,3299.770000,7.000000,0.450000,12414.810000,4.000000,13.000000,560001.000000
max,49999.000000,1.000000e+10,7631.910000,9.000000,0.600000,57792.580000,5.000000,19.000000,751001.000000

In [6]:
df.isnull().sum()

order_id                0
customer_id             0
customer_name        4102
email                4101
phone_number            0
gender                  0
city                 4097
product_category     4074
product_name            0
price                4095
quantity                0
discount                0
final_amount            0
payment_method          0
order_status            0
customer_rating     38553
shipping_days           0
order_date              0
delivery_date           0
pincode             76508
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(5000)

In [8]:
df.columns

Index(['order_id', 'customer_id', 'customer_name', 'email', 'phone_number',
       'gender', 'city', 'product_category', 'product_name', 'price',
       'quantity', 'discount', 'final_amount', 'payment_method',
       'order_status', 'customer_rating', 'shipping_days', 'order_date',
       'delivery_date', 'pincode'],
      dtype='object')

### Data Cleaning

In [9]:
# Dropping the Duplicate data
df = df.drop_duplicates()
df.shape

(225000, 20)

In [10]:
df.duplicated().sum()

np.int64(0)

#### Changing the data types of the columns

In [11]:
# changing the object data type to datetime data type
df['order_date'] = pd.to_datetime(df['order_date'])

In [12]:
# changing the object data type to datetime data type
df['delivery_date'] = pd.to_datetime(df['delivery_date'],format = '%d-%m-%Y')

In [13]:
df['order_date'].dtype

dtype('<M8[ns]')

In [14]:
df['delivery_date'].dtype

dtype('<M8[ns]')

In [15]:
df['pincode'] = df['pincode'].fillna(0).astype('int64')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 225000 entries, 0 to 224999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          225000 non-null  object
 1   customer_id       225000 non-null  int64
 2   customer_name     221000 non-null  object
 3   email             221000 non-null  object
 4   phone_number      225000 non-null  int64
 5   gender            225000 non-null  object
 6   city              221000 non-null  object
 7   product_category  221000 non-null  object
 8   product_name      225000 non-null  object
 9   price             221000 non-null  float64
 10  quantity          225000 non-null  int64
 11  discount          225000 non-null  float64
 12  final_amount      225000 non-null  float64
 13  payment_method    225000 non-null  object
 14  order_status      225000 non-null  object
 15  customer_rating   187331 non-null  float64
 16  shipping_days     225000 non-null  int64
 17  order_date        225000 non-null  datetime64[ns]
 18  delivery_date     225000 non-null  datetime64[ns]
 19  pincode           225000 non-null  int64
dtypes: datetime64[ns](2), float64(4), int64(5), object(9)
memory usage: 36.0+ MB

#### Handling the price issue

In [17]:
df[df['price']<0]

,order_id,customer_id,customer_name,email,phone_number,gender,city,product_category,product_name,price,quantity,discount,final_amount,payment_method,order_status,customer_rating,shipping_days,order_date,delivery_date,pincode
57,ORD100057,36920,Aarav Patel,aarav.patel336@gmail.com,6246801879,male,Kolkata,Groceries,Running Shoes,-111.24,7,0.01,-770.89,COD,Delivered,1.0,11,2022-11-05,2023-10-09,0
61,ORD100061,24939,Karan Mehta,karan.mehta656@gmail.com,7640768496,male,Pune,Fashion,Wireless Mouse,-510.20,1,0.48,-265.30,Wallet,Cancelled,1.0,1,2023-10-24,2024-05-23,0
62,ORD100062,20457,Anjali Singh,anjali.singh75@gmail.com,7809983279,male,Mumbai,Electronics,Running Shoes,-1872.14,9,0.26,-12468.45,Credit Card,Shipped,5.0,17,2024-09-27,2024-11-05,400001
112,ORD100112,23662,Pooja Iyer,pooja.iyer977@gmail.com,9697303769,female,Bangalore,Home,Running Shoes,-3245.93,2,0.24,-4933.81,UPI,Delivered,5.0,4,2024-09-27,2022-02-17,400001
206,ORD100206,48323,Priya Iyer,priya.iyer770@gmail.com,8444530296,Female,Delhi,Electronics,Running Shoes,-621.07,1,0.19,-503.07,Debit Card,Cancelled,4.0,17,2022-04-23,2022-05-31,751001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224727,ORD324727,40270,Karan Gupta,karan.gupta336@gmail.com,8832245780,M,Chennai,Home,Office Chair,-189.81,8,0.29,-1078.12,Credit Card,Shipped,4.0,19,2023-11-21,2024-09-25,0
224767,ORD324767,48464,Rohit Singh,rohit.singh596@gmail.com,9207472152,M,Pune,Sports,Wireless Mouse,-1278.86,3,0.35,-2493.78,Debit Card,Delivered,2.0,11,2022-02-24,2024-02-01,0
224869,ORD324869,11402,Priya Iyer,priya.iyer487@gmail.com,8667627838,male,Bangalore,Electronics,Office Chair,-460.11,4,0.20,-1472.35,UPI,Delivered,NaN,18,2024-01-24,2023-07-20,0
224980,ORD324980,15847,Aarav Patel,aarav.patel132@gmail.com,9855533128,female,Bangalore,Home,Office Chair,-372.13,9,0.02,-3282.19,Debit Card,Shipped,3.0,10,2022-02-28,2023-01-27,0
224989,ORD324989,11001,Aarav Gupta,aarav.gupta236@gmail.com,9260526427,F,Kolkata,Beauty,Coffee Maker,-2153.31,3,0.53,-3036.17,Wallet,Shipped,5.0,-2,2022-05-25,2024-12-16,0

In [18]:
# Fitering the rows where price is greater than zero 
df = df[df['price']>0]

In [19]:
df[df['price']<0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, email, phone_number, gender, city, product_category, product_name, price, quantity, discount, final_amount, payment_method, order_status, customer_rating, shipping_days, order_date, delivery_date, pincode]
Index: []

Detected 5952 recodrs containing negative product price (2.4% of the dataset).
since negative price was inconsistent with the dataset business context, 
these records were treated as invalid and removed to ensure relaible revenue pricing analysis

In [20]:
df.shape

(215048, 20)

In [21]:
df.isnull().sum()

order_id                0
customer_id             0
customer_name        3803
email                3812
phone_number            0
gender                  0
city                 3837
product_category     3824
product_name            0
price                   0
quantity                0
discount                0
final_amount            0
payment_method          0
order_status            0
customer_rating     35997
shipping_days           0
order_date              0
delivery_date           0
pincode                 0
dtype: int64

In [22]:
df[df['final_amount']<0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, email, phone_number, gender, city, product_category, product_name, price, quantity, discount, final_amount, payment_method, order_status, customer_rating, shipping_days, order_date, delivery_date, pincode]
Index: []

#### Handling the pincode issue

In [23]:
df['city'].unique()

array(['Chennai', 'Delhi', 'Kolkata', 'Bangalore', 'Hyderabad', 'Pune',
       'Mumbai', 'Ahmedabad', nan, 'mumbai', 'pune', 'delhi', 'chennai',
       'hyderabad', 'kolkata', 'ahmedabad', 'bangalore'], dtype=object)

In [24]:
# Removing the extra space and converting the city name in lower case
df['city'] = df['city'].str.strip().str.lower()

In [25]:
df['city'].unique()

array(['chennai', 'delhi', 'kolkata', 'bangalore', 'hyderabad', 'pune',
       'mumbai', 'ahmedabad', nan], dtype=object)

In [26]:
df[['city','pincode']]

             city  pincode
0         chennai   400001
1           delhi        0
2         kolkata   751001
3       bangalore        0
4       hyderabad   400001
...           ...      ...
224995      delhi   400001
224996  bangalore   751001
224997      delhi   751001
224998    kolkata        0
224999    chennai        0

[215048 rows x 2 columns]

In [27]:
df.groupby('pincode')['city'].nunique()

pincode
0         8
400001    8
560001    8
751001    8
Name: city, dtype: int64

In [28]:
df[df['pincode']==0]

,order_id,customer_id,customer_name,email,phone_number,gender,city,product_category,product_name,price,quantity,discount,final_amount,payment_method,order_status,customer_rating,shipping_days,order_date,delivery_date,pincode
1,ORD100001,1860,Arjun Reddy,arjun.reddy618@gmail.com,7710434697,Female,delhi,Groceries,Running Shoes,1829.71,7,0.26,9477.90,UPI,Shipped,NaN,17,2022-04-25,2024-12-08,0
3,ORD100003,45732,Priya Singh,priya.singh269@gmail.com,7562339125,F,bangalore,Beauty,Smartphone,2066.98,8,0.50,8267.92,UPI,Delivered,NaN,-2,2022-01-29,2024-11-12,0
10,ORD100010,45131,Sneha Singh,sneha.singh487@gmail.com,8785441974,male,hyderabad,Sports,Wireless Mouse,4569.48,9,0.50,20562.66,COD,Cancelled,2.0,-3,2022-06-28,2022-11-27,0
11,ORD100011,17023,Karan Reddy,NaN,9606272019,Female,NaN,Electronics,Running Shoes,495.97,8,0.10,3570.98,Debit Card,Cancelled,4.0,3,2023-06-03,2023-11-03,0
13,ORD100013,2685,Arjun Sharma,arjun.sharma527@gmail.com,6198679999,Male,mumbai,Groceries,Running Shoes,1847.22,9,0.56,7314.99,Debit Card,Delivered,2.0,-5,2023-02-25,2024-09-19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224991,ORD324991,12107,Arjun Gupta,arjun.gupta8@gmail.com,7063904984,Male,ahmedabad,Beauty,Smartphone,3915.20,5,0.20,15660.80,UPI,Delivered,NaN,-4,2024-07-27,2023-05-02,0
224992,ORD324992,33603,Neha Mehta,neha.mehta349@gmail.com,6515040847,Male,chennai,Sports,Running Shoes,2141.85,2,0.29,3041.43,COD,Shipped,5.0,0,2025-02-03,2023-05-21,0
224993,ORD324993,48245,Pooja Reddy,pooja.reddy570@gmail.com,9953779227,F,ahmedabad,Groceries,Coffee Maker,2375.75,5,0.24,9027.85,Debit Card,Shipped,1.0,12,2023-06-24,2024-05-31,0
224998,ORD324998,18668,Karan Khan,..karan.khan.735@gmail.com,8031602835,M,kolkata,Groceries,Smartphone,772.37,5,0.09,3514.28,Debit Card,Shipped,2.0,6,2022-03-17,2022-03-08,0
224999,ORD324999,21038,Arjun Verma,arjun.verma224@gmail.com,9190799271,female,chennai,Home,Office Chair,1358.24,9,0.18,10023.81,Wallet,Shipped,1.0,17,2023-08-25,2022-11-06,0

In [29]:
#Droping the pincode column because it contain inconsistent value
df.drop(columns = ['pincode'], inplace = True)

Dropped pincode column due to high missing value(approx 33%) and inconsistent mapping across multiple cities making the field unreliable for analysis

#### Product Category Standardization

In [31]:
df['product_category'].unique()

array(['Fashion', 'Groceries', nan, 'Beauty', 'Sports', 'Books', 'Home',
       'Electronics'], dtype=object)

In [32]:
df['product_name'].unique()

array(['Coffee Maker', 'Running Shoes', 'Office Chair', 'Smartphone',
       'Wireless Mouse'], dtype=object)

In [33]:
df[['product_category','product_name']]

       product_category   product_name
0               Fashion   Coffee Maker
1             Groceries  Running Shoes
2                   NaN   Office Chair
3                Beauty     Smartphone
4                Sports     Smartphone
...                 ...            ...
224995          Fashion   Coffee Maker
224996           Beauty   Coffee Maker
224997        Groceries     Smartphone
224998        Groceries     Smartphone
224999             Home   Office Chair

[215048 rows x 2 columns]

In [34]:
def map_category(product_name):
    product_name = product_name.lower()
    if 'running shoes' in product_name:
        return 'Fashion'
    elif 'office chair' in product_name or 'coffee maker' in product_name:
        return 'Home'
    elif 'wireless mouse' in product_name or 'smartphone' in product_name:
        return 'Electronics'
    else:
        return 'Other'
df['category'] = df['product_name'].apply(map_category)

In [35]:
df[['category','product_name']]

           category   product_name
0              Home   Coffee Maker
1           Fashion  Running Shoes
2              Home   Office Chair
3       Electronics     Smartphone
4       Electronics     Smartphone
...             ...            ...
224995         Home   Coffee Maker
224996         Home   Coffee Maker
224997  Electronics     Smartphone
224998  Electronics     Smartphone
224999         Home   Office Chair

[215048 rows x 2 columns]

In [36]:
# droping the product_category column as new category column is created with correct mapping
df.drop(columns = ['product_category'],inplace = True)

In [37]:
df['category'].unique()

array(['Home', 'Fashion', 'Electronics'], dtype=object)

In [38]:
df['product_name'].unique()

array(['Coffee Maker', 'Running Shoes', 'Office Chair', 'Smartphone',
       'Wireless Mouse'], dtype=object)

A significat mismatch was observed between product category and product name, incating unreliable categorical labeling. Due to inconsistent mapping,
product category were not used directly for analysis

In [39]:
df.isnull().sum()

order_id               0
customer_id            0
customer_name       3803
email               3812
phone_number           0
gender                 0
city                3837
product_name           0
price                  0
quantity               0
discount               0
final_amount           0
payment_method         0
order_status           0
customer_rating    35997
shipping_days          0
order_date             0
delivery_date          0
category               0
dtype: int64

#### Customer Rating Standardization

In [40]:
df['customer_rating'].unique()

array([ 2., nan,  3.,  5.,  4.,  1.])

In [41]:
df['customer_rating'].dtype

dtype('float64')

In [42]:
df['customer_rating'].isnull().mean()*100

np.float64(16.73905360663666)

In [44]:
# filling the missing value with median
df['customer_rating'] = df.groupby('category')['customer_rating'].transform(lambda x:x.fillna(x.median()))

In [45]:
df.isnull().sum()

order_id              0
customer_id           0
customer_name      3803
email              3812
phone_number          0
gender                0
city               3837
product_name          0
price                 0
quantity              0
discount              0
final_amount          0
payment_method        0
order_status          0
customer_rating       0
shipping_days         0
order_date            0
delivery_date         0
category              0
dtype: int64

#### Customer name Integrity Checks

In [47]:
df['customer_name'].unique()

array(['Priya Sharma', 'Arjun Reddy', 'Sneha Khan', 'Priya Singh',
       'Priya Mehta', 'Karan Sharma', 'Aarav Patel', 'Sneha Reddy',
       'Rohit Mehta', 'Aarav Singh', 'Sneha Singh', 'Karan Reddy',
       'Anjali Mehta', 'Arjun Sharma', 'Rahul Iyer', 'Pooja Verma',
       'Rahul Reddy', 'Pooja Patel', 'Priya Iyer', 'Priya Das',
       'Pooja Mehta', 'Anjali Singh', 'Arjun Mehta', 'Sneha Patel',
       'Aarav Reddy', 'Arjun Patel', '  Sneha Patel ', 'Karan Verma',
       'Anjali Das', 'Rahul Das', 'Pooja Reddy', 'Neha Khan',
       'Rohit Reddy', 'Rahul Gupta', 'Pooja Sharma', 'Sneha Sharma',
       'Pooja Iyer', 'Sneha Mehta', 'Anjali Iyer', 'Anjali Khan',
       'Arjun Khan', 'Rohit Verma', 'Neha Iyer', 'Rahul Singh',
       'Anjali Patel', 'Rahul Khan', 'Karan Mehta', 'Arjun Singh',
       'Arjun Iyer', 'Aarav Verma', 'Rohit Khan', 'Rohit Patel',
       'Neha Reddy', 'Rohit Sharma', 'Neha Das', 'Anjali Sharma',
       '  Aarav Reddy ', 'Neha Patel', 'Priya Gupta', 'Rahul Verma',
       'Pooja Gupta', 'Rohit Gupta', 'Priya Reddy', 'Neha Singh',
       '  Priya Sharma ', 'Aarav Das', 'Sneha Verma', 'Anjali Reddy',
       'Neha Mehta', 'Karan Gupta', 'Aarav Iyer', '  Pooja Patel ',
       'Karan Khan', 'Arjun Gupta', 'Anjali Gupta', 'Sneha Iyer',
       'Aarav Khan', 'Anjali Verma', 'Karan Singh', 'Aarav Sharma',
       'Neha Gupta', 'Rohit Singh', 'Rahul Sharma', 'Rahul Patel',
       'Neha Sharma', 'Sneha Das', nan, 'Priya Patel', 'Arjun Verma',
       'Pooja Khan', 'Priya Khan', 'Pooja Singh', 'Aarav Gupta',
       'Priya Verma', 'Rahul Mehta', 'Karan Das', 'Karan Patel',
       'Karan Iyer', 'Neha Verma', 'Sneha Gupta', 'Pooja Das',
       'Aarav Mehta', '  Karan Das ', 'Arjun Das', 'Rohit Das',
       'Rohit Iyer', '  Priya Patel ', '  Pooja Singh ', '  Aarav Khan ',
       '  Anjali Iyer ', '  Karan Patel ', '  Anjali Singh ',
       '  Priya Mehta ', '  Anjali Mehta ', '  Arjun Reddy ',
       '  Sneha Sharma ', '  Arjun Mehta ', '  Anjali Reddy ',
       '  Rahul Singh ', '  Sneha Gupta ', '  Pooja Reddy ',
       '  Rohit Gupta ', '  Anjali Gupta ', '  Rohit Singh ',
       '  Anjali Das ', '  Priya Das ', '  Anjali Sharma ',
       '  Aarav Sharma ', '  Pooja Sharma ', '  Arjun Gupta ',
       '  Aarav Verma ', '  Rahul Iyer ', '  Neha Reddy ',
       '  Neha Verma ', '  Karan Mehta ', '  Sneha Mehta ',
       '  Neha Sharma ', '  Rahul Patel ', '  Neha Iyer ',
       '  Priya Singh ', '  Karan Gupta ', '  Neha Patel ',
       '  Neha Singh ', '  Arjun Iyer ', '  Rahul Das ', '  Aarav Iyer ',
       '  Priya Reddy ', '  Karan Khan ', '  Neha Gupta ',
       '  Anjali Khan ', '  Pooja Verma ', '  Rohit Verma ',
       '  Rohit Khan ', '  Rohit Mehta ', '  Priya Gupta ',
       '  Sneha Khan ', '  Karan Singh ', '  Aarav Patel ',
       '  Neha Khan ', '  Arjun Khan ', '  Pooja Gupta ',
       '  Arjun Sharma ', '  Rahul Khan ', '  Rohit Patel ',
       '  Rahul Mehta ', '  Rohit Reddy ', '  Pooja Das ',
       '  Arjun Patel ', '  Sneha Reddy ', '  Aarav Das ',
       '  Karan Iyer ', '  Arjun Das ', '  Pooja Khan ',
       '  Anjali Verma ', '  Rohit Sharma ', '  Karan Sharma ',
       '  Rohit Iyer ', '  Rahul Reddy ', '  Aarav Singh ',
       '  Priya Verma ', '  Sneha Singh ', '  Priya Khan ',
       '  Pooja Mehta ', '  Aarav Gupta ', '  Sneha Das ',
       '  Karan Reddy ', '  Rahul Sharma ', '  Arjun Singh ',
       '  Karan Verma ', '  Sneha Verma ', '  Pooja Iyer ',
       '  Neha Mehta ', '  Rahul Gupta ', '  Sneha Iyer ', '  Neha Das ',
       '  Arjun Verma ', '  Anjali Patel ', '  Rahul Verma ',
       '  Aarav Mehta ', '  Priya Iyer ', '  Rohit Das '], dtype=object)

In [48]:
# Removing the extra spaces and converting into lower case
df['customer_name'] = df['customer_name'].str.strip().str.lower()

In [49]:
# Filling the missing value with unkown
df['customer_name'] = df['customer_name'].fillna('unknown customer')

In [50]:
df.isnull().sum()

order_id              0
customer_id           0
customer_name         0
email              3812
phone_number          0
gender                0
city               3837
product_name          0
price                 0
quantity              0
discount              0
final_amount          0
payment_method        0
order_status          0
customer_rating       0
shipping_days         0
order_date            0
delivery_date         0
category              0
dtype: int64

#### Checking the email column

In [51]:
df['email'].unique()

array(['priya.sharma678@gmail.com', 'arjun.reddy618@gmail.com', nan, ...,
       '..pooja.verma.606@gmail.com', 'arjun.gupta8@gmail.com',
       '..karan.khan.735@gmail.com'], shape=(95039,), dtype=object)

In [52]:
# Removing the extra space
df['email'] = df['email'].str.strip().str.lower()

In [53]:
# filling the missing value with 'no email provide'
df['email'] = df['email'].fillna('no email provided')

In [54]:
df.isnull().sum()

order_id              0
customer_id           0
customer_name         0
email                 0
phone_number          0
gender                0
city               3837
product_name          0
price                 0
quantity              0
discount              0
final_amount          0
payment_method        0
order_status          0
customer_rating       0
shipping_days         0
order_date            0
delivery_date         0
category              0
dtype: int64

In [55]:
# filling the missing city name with unkown
df['city'] = df['city'].fillna('unknown')

In [56]:
df.isnull().sum()

order_id           0
customer_id        0
customer_name      0
email              0
phone_number       0
gender             0
city               0
product_name       0
price              0
quantity           0
discount           0
final_amount       0
payment_method     0
order_status       0
customer_rating    0
shipping_days      0
order_date         0
delivery_date      0
category           0
dtype: int64

#### Gender column integrity checks

In [57]:
df['gender'].unique()

array(['male', 'Female', 'F', 'female', 'Male', 'M'], dtype=object)

In [58]:
# Removing the extra spaces
df['gender'] = df['gender'].str.strip().str.lower()

In [59]:
df['gender'].unique()

array(['male', 'female', 'f', 'm'], dtype=object)

In [60]:
# Mapping gender values
df['gender'] = df['gender'].replace({
                                        'male':'male',
                                        'm': 'male',
                                        'female':'female',
                                        'f':'female'}
                                   )

In [61]:
df['gender'].unique()

array(['male', 'female'], dtype=object)

In [62]:
df.columns

Index(['order_id', 'customer_id', 'customer_name', 'email', 'phone_number',
       'gender', 'city', 'product_name', 'price', 'quantity', 'discount',
       'final_amount', 'payment_method', 'order_status', 'customer_rating',
       'shipping_days', 'order_date', 'delivery_date', 'category'],
      dtype='object')

In [63]:
# Checking the payment method
df['payment_method'].unique()

array(['Credit Card', 'UPI', 'Debit Card', 'Wallet', 'COD'], dtype=object)

In [64]:
# Checking the order status
df['order_status'].unique()

array(['Shipped', 'Delivered', 'Pending', 'Cancelled', 'Returned'],
      dtype=object)

In [65]:
df['customer_rating'].unique()

array([2., 3., 5., 4., 1.])

In [66]:
df['category'].unique()

array(['Home', 'Fashion', 'Electronics'], dtype=object)

In [67]:
df.describe()

,customer_id,phone_number,price,quantity,discount,final_amount,customer_rating,shipping_days,order_date,delivery_date
count,215048.000000,2.150480e+05,215048.000000,215048.000000,215048.000000,215048.000000,215048.000000,215048.000000,215048,215048
mean,25453.644977,7.998162e+09,2553.513644,5.006501,0.299352,8952.276961,3.004794,6.980669,2023-08-23 17:28:11.990625536,2023-08-23 21:15:29.295784960
min,1000.000000,6.000002e+09,0.040000,1.000000,0.000000,0.190000,1.000000,-5.000000,2022-01-01 00:00:00,2022-01-01 00:00:00
25%,13226.750000,7.001244e+09,1740.635000,3.000000,0.150000,3517.535000,2.000000,1.000000,2022-10-27 00:00:00,2022-10-26 00:00:00
50%,25392.500000,7.997719e+09,2525.345000,5.000000,0.300000,7259.920000,3.000000,7.000000,2023-08-25 00:00:00,2023-08-24 00:00:00
75%,37698.250000,8.996533e+09,3326.135000,7.000000,0.450000,12605.590000,4.000000,13.000000,2024-06-18 00:00:00,2024-06-20 00:00:00
max,49999.000000,1.000000e+10,7631.910000,9.000000,0.600000,57792.580000,5.000000,19.000000,2025-04-15 00:00:00,2025-04-15 00:00:00
std,14125.371387,1.152745e+09,1138.496031,2.582841,0.173137,6984.197866,1.290242,7.211661,NaN,NaN

#### Handling inconsistent shipping days

In [68]:
df['shipping_days'].unique()

array([14, 17, 11, -2,  7, -5, 16,  5, 12, -3,  3,  9, 10, 18, -4,  6,  8,
       13, 19,  1,  2, 15, -1,  4,  0])

In [69]:
# Dropping the shipping_days because of inconsitent value
df.drop(columns = ['shipping_days'], inplace = True)

In [72]:
# Recalculating the shipping days
df['shipping_days'] = (df['delivery_date']-df['order_date']).dt.days

In [82]:
df.shape

(215048, 19)

In [74]:
df[df['shipping_days']<0]

,order_id,customer_id,customer_name,email,phone_number,gender,city,product_name,price,quantity,discount,final_amount,payment_method,order_status,customer_rating,order_date,delivery_date,category,shipping_days
0,ORD100000,16795,priya sharma,priya.sharma678@gmail.com,6920626990,male,chennai,Coffee Maker,2930.24,2,0.46,3164.66,Credit Card,Shipped,2.0,2023-10-03,2022-02-11,Home,-599
5,ORD100005,7265,karan sharma,karan.sharma112@gmail.com,9105407187,male,pune,Coffee Maker,3645.49,6,0.15,18592.00,UPI,Pending,3.0,2024-12-12,2024-02-11,Home,-305
7,ORD100007,38194,sneha reddy,sneha.reddy424@gmail.com,6765411064,male,kolkata,Running Shoes,2529.19,1,0.06,2377.44,Wallet,Cancelled,5.0,2022-04-16,2022-04-10,Fashion,-6
9,ORD100009,48191,aarav singh,aarav.singh617@gmail.com,9617280131,male,ahmedabad,Running Shoes,930.71,6,0.40,3350.56,UPI,Shipped,3.0,2022-05-26,2022-02-27,Fashion,-88
12,ORD100012,42090,anjali mehta,anjali.mehta788@gmail.com,8541874364,male,kolkata,Coffee Maker,3689.51,8,0.19,23908.02,Debit Card,Pending,3.0,2025-02-11,2023-09-09,Home,-521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224992,ORD324992,33603,neha mehta,neha.mehta349@gmail.com,6515040847,male,chennai,Running Shoes,2141.85,2,0.29,3041.43,COD,Shipped,5.0,2025-02-03,2023-05-21,Fashion,-624
224994,ORD324994,8859,sneha mehta,sneha.mehta971@gmail.com,8275387324,male,ahmedabad,Coffee Maker,2535.11,3,0.49,3878.72,Wallet,Returned,5.0,2024-05-20,2023-12-16,Home,-156
224997,ORD324997,26757,neha reddy,neha.reddy500@gmail.com,9606247459,female,delhi,Smartphone,3992.48,8,0.17,26510.07,UPI,Cancelled,2.0,2023-12-07,2022-02-28,Electronics,-647
224998,ORD324998,18668,karan khan,..karan.khan.735@gmail.com,8031602835,male,kolkata,Smartphone,772.37,5,0.09,3514.28,Debit Card,Shipped,2.0,2022-03-17,2022-03-08,Electronics,-9
224999,ORD324999,21038,arjun verma,arjun.verma224@gmail.com,9190799271,female,chennai,Office Chair,1358.24,9,0.18,10023.81,Wallet,Shipped,1.0,2023-08-25,2022-11-06,Home,-292

In [83]:
swap_conditions = df['delivery_date']<df['order_date']

In [85]:
df.loc[swap_conditions,['order_date','delivery_date']]= df.loc[swap_conditions,['delivery_date','order_date']].values

In [75]:
# Replacing the negative values with nan
df.loc[df['shipping_days']<0,'shipping_days'] = np.nan

In [77]:
df[df['shipping_days']<0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, email, phone_number, gender, city, product_name, price, quantity, discount, final_amount, payment_method, order_status, customer_rating, order_date, delivery_date, category, shipping_days]
Index: []

In [88]:
df.head()

,order_id,customer_id,customer_name,email,phone_number,gender,city,product_name,price,quantity,discount,final_amount,payment_method,order_status,customer_rating,order_date,delivery_date,category,shipping_days
0,ORD100000,16795,priya sharma,priya.sharma678@gmail.com,6920626990,male,chennai,Coffee Maker,2930.24,2,0.46,3164.66,Credit Card,Shipped,2.0,2022-02-11,2023-10-03,Home,NaN
1,ORD100001,1860,arjun reddy,arjun.reddy618@gmail.com,7710434697,female,delhi,Running Shoes,1829.71,7,0.26,9477.90,UPI,Shipped,3.0,2022-04-25,2024-12-08,Fashion,958.0
2,ORD100002,39158,sneha khan,no email provided,6647628669,male,kolkata,Office Chair,3009.13,5,0.56,6620.09,UPI,Shipped,3.0,2023-12-08,2024-08-22,Home,258.0
3,ORD100003,45732,priya singh,priya.singh269@gmail.com,7562339125,female,bangalore,Smartphone,2066.98,8,0.50,8267.92,UPI,Delivered,3.0,2022-01-29,2024-11-12,Electronics,1018.0
4,ORD100004,12284,priya mehta,priya.mehta751@gmail.com,9679292386,female,hyderabad,Smartphone,1374.45,9,0.29,8782.74,Debit Card,Pending,5.0,2023-10-12,2023-10-25,Electronics,13.0

In [92]:
df[df['shipping_days']<0]

Empty DataFrame
Columns: [order_id, customer_id, customer_name, email, phone_number, gender, city, product_name, price, quantity, discount, final_amount, payment_method, order_status, customer_rating, order_date, delivery_date, category, shipping_days]
Index: []

In [95]:
df.to_csv('Ecommerce_sales_date_after_cleaning.csv',index = False)